Repository godotengine/godot-benchmarks, pull requests merged in 2024-04, with the labels that each got.

#60 Added PointLight2D and DirectionalLight2D benchmarks
  benchmarks/math/expression.gd
  benchmarks/rendering/lights_2d.gd
  benchmarks/rendering/sdfgi.gd
  supplemental/2d_point_light_texture.png
  supplemental/2d_point_light_texture.png.import
Labels: enhancement

#44 Implement scene nodes benchmarks
  benchmarks/scene_nodes/add_children.gd
  benchmarks/scene_nodes/delete_children.gd
  benchmarks/scene_nodes/get_node.gd
  benchmarks/scene_nodes/move_children.gd
Labels: enhancement

#39 Implement a benchmark algorithm `Delaunay3D`
  benchmarks/math/delaunay_3d.gd
Labels: enhancement

#61 Add benchmark for viewport creation/activation
  benchmarks/viewport/activation.gd
  benchmarks/viewport/allocation.gd
  manager.gd
Labels: enhancement

#62 Add GPUParticles2D and CPUParticles2D benchmarks
  benchmarks/rendering/particles_2d.gd
Labels: enhancement

#63 Add graphs to the website
  benchmarks/math/expression_gen.py
  web/.gitignore
  web/generate-content.py
  web/layouts/_default/baseof.html
  web/layouts/benchmark/single.html
  web/layouts/graph/single.html
  web/layouts/index.html
  web/src-data/graphs.json
  web/static/graphs.js
Labels: enhancement, topic:website

#64 Improve docs and simplify/fix setup
  web/README.md
  web/data/.gitkeep
  web/generate-content.py
  web/src-data/benchmarks/.gitkeep
Labels: bug, documentation
